config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "new-job", to: "sessions#new"
  post "new-job", to: "sessions#create"

  get "jobs", to: "jobs#index"

  get "about-us", to: "about#index"

  # Defines the root path route ("/")
   root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:name, :salary, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @job = Jobs.new
    end

    def create
        @job = Jobs.new(job_params)
        if @job.save 
           session[:job_id] = @job.id
           redirect_to root_path, notice: "Successfully submitted the job"
        else
           render :new
        end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/about/index.html.erb
<h1>About</h1>
<h3> We are a company that find people jobs</h3>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Job title", style: "display: block" %>
   <%= form.text_field :name, placeholder:"Gardener",:size => 50%>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.text_field :salary, value:"£",:size => 50 %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, placeholder: "Gardening job in located in the heart of Sheffield.",:size => 50 %>
  </div>

  <div class="but">
    <%= form.submit %>
  </div>
<% end %>

<style>

.but{
  padding-top: 10px;
}
</style>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
 <center>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> <%= job.name %></h5>
    <h6 class="card-text"><%= job.salary %></h6>
   <p class="card-text"><%= job.description %></p>
   <%= link_to "Show this job", job %>
   
   
  </div>
</div>
</center>
</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>

<div id="jobs">
  <% @jobs.each do |job| %>
    <%= render job %>
    <br>
  <% end %>
</div>

<%= link_to "New job", new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   <script src="https://kit.fontawesome.com/9204d86091.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

   <%= render partial: "shared/navbar" %>
   <div class="container">
  
   <%= render partial: "shared/flash"%>
    <%= yield %>
    
    
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1> Welcome to the Job board</h1>
<br>
<h2>Use the navigation bar to find your way around</h2>

    <br>
    <br>
    <br>
    <h3>Job of the day:</h3>

    

app/views/shared/_flash.html.erb
<%# <% if flash[:notice]%>
<%#<div class="alert alert-info mt-4" role="alert">
<%= flash[:notice]%>
<%#</div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar  navbar-expand-lg navbar-light bg-#B33951 textcolor-black">
  <div class="container-fluid">
            <i class="fa-solid fa-briefcase fa-2xl"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "Jobs", jobs_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
         <%= link_to "About", about_us_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-end">
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Job Options
          </a>
          <ul class="dropdown-menu dropdown-menu-end " aria-labelledby="navbarDropdownMenuLink">
            <li class="nav-item">
         <%= link_to "New Job", new_job_path, class: "nav-link" %>
         <%= link_to "View Jobs", jobs_path, class: "nav-link" %>
        </li>
          </ul>
        </li>
        </ul>
    </div>
  </div>
</nav>